name: Convert HTML to PDF
description: |
  Converts HTML files into PDF using chrome-headless-render-pdf
branding:
  icon: file-text
  color: gray-dark
input:
  htmlPath:
    required: true
    default: index.html
  pdfName:
    required: true
    default: output
runs:
  using: docker
  image: Dockerfile
  args:
  - ${{ inputs.htmlPath }}
  - ${{ inputs.pdfName }}
